export default {
  login: 'Mojgan360',
  id: 8652674,
  node_id: 'MDQ6VXNlcjg2NTI2NzQ=',
  avatar_url: 'https://avatars1.githubusercontent.com/u/8652674?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Mojgan360',
  html_url: 'https://github.com/Mojgan360',
  followers_url: 'https://api.github.com/users/Mojgan360/followers',
  following_url:
    'https://api.github.com/users/Mojgan360/following{/other_user}',
  gists_url: 'https://api.github.com/users/Mojgan360/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/Mojgan360/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Mojgan360/subscriptions',
  organizations_url: 'https://api.github.com/users/Mojgan360/orgs',
  repos_url: 'https://api.github.com/users/Mojgan360/repos',
  events_url: 'https://api.github.com/users/Mojgan360/events{/privacy}',
  received_events_url: 'https://api.github.com/users/Mojgan360/received_events',
  type: 'User',
  site_admin: false,
  name: 'Mojgan',
  company: 'MediaAx',
  blog: 'https://mojgan.netlify.app/',
  location: 'Sweden',
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 31,
  public_gists: 0,
  followers: 1,
  following: 10,
  created_at: '2014-09-04T07:34:47Z',
  updated_at: '2020-09-21T12:46:45Z',
}
